import os
import sys
from pathlib import Path

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utilities.maps import M

input_path = Path(__file__).parent / "input.txt"
input = input_path.read_text()

# --- Logic ---


def find_anti_nodes(
    i: int,
    all: list[tuple[int, int]],
    map: M,
) -> set[tuple[int, int]]:
    if i >= len(all):
        return set()

    a = all[i]
    others = all[:i] + all[i + 1 :]

    antinodes = set()
    for o in others:
        # find antenna reflect position compared to r
        x, y = (
            o[0] + (o[0] - a[0]),
            o[1] + (o[1] - a[1]),
        )

        if map.out(x, y):
            continue

        antinodes.add((x, y))

    return find_anti_nodes(i + 1, all, map).union(antinodes)


def logic(input: str) -> int:
    map = M(input)
    antennas_by_type = map.list_points()

    antinodes = set()
    for v, antennas in antennas_by_type.items():
        nodes = find_anti_nodes(0, antennas, map)
        antinodes.update(nodes)

    return len(antinodes)


# --- Example ---


def test_example_1():
    example = """
    ..........
    ..........
    ..........
    ..........
    ....a.....
    ........a.
    .....a....
    ..........
    ..........
    ..........
    ..........
    """
    assert logic(example) == 4


def test_example_2():
    example = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    """
    assert logic(example) == 10


def test_example_3():
    example = """
    ............
    ............
    ............
    ............
    ............
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """
    assert logic(example) == 5


def test_example_4():
    example = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """
    assert logic(example) == 14


# --- Input ---


def test_input():
    result = logic(input)
    assert result == 323
